#!/usr/bin/env bash
#  Nginx to run as the nginx user.
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
echo "user nginx" | tee -a /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx 
service nginx start
