#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install apache2
sudo service apache2 start
sudo service apache2 status
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo service apache2 restart
